### ISSUE TITLE
Issue with eem_coble_peaks() function

### ISSUE THREAD

**Issue by Nawal-ctrl** [MatthiasPucher/staRdom#10]
Hello, 
I have an issue with when I run eem_coble_peaks() function. I get a warning message 

> `This metric uses either excitation or emission wavelengths that were not present in the data. Data has been interpolated to fit the requested wavelengths.`

followed by an error :

> Error in findInterval(xp, x) : 
>   'vec' must be sorted non-decreasingly and not contain NAs

The function stops there

I can't determine what is causing this exactly. Any suggestions

**Comment by MatthiasPucher** [comment]
Without seeing the data, I just have a guess:
Please check the data you provide for NAs and if the wavelengths used for the coble peaks are present in the data as well.
eem_coble_peaks is a function of eemR, so you might also find helpful advice here: https://github.com/PMassicotte/eemR

**Comment by Nawal-ctrl** [comment]
Thank you, the link was useful. There was no NAs, but it seems that I chose the wrong option to read my EEMs (from aqualog). I am not sure to understand how it really worked but it did as soon as I put "aqualog"  to read my data.
