### ISSUE TITLE
Absorption coefficient

### ISSUE THREAD

**Issue by liberty0117** [MatthiasPucher/staRdom#11]

**Comment by MatthiasPucher** [comment]
I am curious about what you wrote in April, but I could not understand totally.
staRdom can calculate the exponential slope between 300 and 700 using abs_parms. You can set  custom limits using the limits = ...
Could you maybe clarify, what you would like to do more in detail?
I am aware of an interesting method, described in 10.1046/j.1365-2087.1998.00086.x
But it is not implemented so far in staRdom, still on my todo list.

**Comment by liberty0117** [comment]
Thank you very much for your reply.In fact, what I want to express in April was whether the every absorption coefficient value (250-700nm) of each sample can be directly calculated with the package. Thus, the exponential decay curve can be easily made.However, considering that this is only a function of computation and is not necessarily implemented in this package, I turned this off.Anyway, thank you very much for developing such a great package.


| |
李典宝
|
|
liberty0117@163.com
|
签名由网易邮箱大师定制
On 7/13/2020 19:36，MatthiasPucher<notifications@github.com> wrote：

I am curious about what you wrote in April, but I could not understand totally.
staRdom can calculate the exponential slope between 300 and 700 using abs_parms. You can set custom limits using the limits = ...
Could you maybe clarify, what you would like to do more in detail?
I am aware of an interesting method, described in 10.1046/j.1365-2087.1998.00086.x
But it is not implemented so far in staRdom, still on my todo list.
