### ISSUE TITLE
Error in parafac_conv

### ISSUE THREAD

**Issue by ChiaraCooper** [MatthiasPucher/staRdom#12]
Hi Matthias, 

Thank you for your package first of all! 

I have an issue with parafac_conv. When I try to run it with the parameter output="all" it returns this:

Error in parafac_conv(eem_array, nfac = comp, const = const, maxit = maxit,  : 
  formal argument "output" matched by multiple actual arguments

>mod3exclude<-eem_parafac(eem_list_exclude,comps=4,normalise=TRUE,const=c("nonneg","nonneg","nonneg"),maxit=maxit,nstart=nstart,output="all",ctol=ctol,cores=cores)
Error in parafac_conv(eem_array, nfac = comp, const = const, maxit = maxit,  : 
  formal argument "output" matched by multiple actual arguments

Thank you,

Chiara

**Comment by MatthiasPucher** [comment]
Thank you for leaving a comment!
It is fixed in the current GitHub version. CRAN will follow in some days!
Sorry for letting you wait!
