### ISSUE TITLE
abs_blcor bug when there's only one absorbance spectrum

### ISSUE THREAD

**Issue by mooaw** [MatthiasPucher/staRdom#15]
Hi Matthias,

I recently found a bug with abs_blcor function. If I only have one absorbance spectrum in my abs data, after baseline correction, the data will lose its data frame structure and the name of spectrum. And it can't be directly used for IFE correction. In that case, I have to manually reformat the data into a data frame and provide the name. It's not a big problem but may be confusing at first. I hope it can be fixed.

Thanks again for creating this wonderful package!

Best,
Jianshu

**Comment by MatthiasPucher** [comment]
Thank you for bringing this up. It was no big problem and is fixed with the recent version on GitHub.
