### ISSUE TITLE
Core consistency calculation

### ISSUE THREAD

**Issue by Taojianchang** [MatthiasPucher/staRdom#18]
Thanks for the package ! 
I have few confusions about calculating the core consistency. I have done the Raman normalization with my original data. But result from corcondia <- eempf_corcondia(pfmodel, eem_list) with 3 to 6 components were in the range of 9 to 10. It seemed I can't get a fine core consistency value. Do I need to do any other normalizations ?

**Comment by MatthiasPucher** [comment]
The pre-processing of the data is explained in the vignette and I would suggest to remove scatter, interpolate, IFE correction, Raman normalisation and calculating the PARAFAC model with normalised samples (no extra step, just an optional argument). The core consistency might be extremely severe with real-life fluorescence data. The following paper has some information on that.

Bro, R. PARAFAC. Tutorial and applications. Chemom. Intell. Lab. Syst. 1997, 38, 149–171.

Could you please consider this case. If you suspect a problem in the R code please do not hesitate to discuss it here.

**Comment by MatthiasPucher** [comment]
A bug in the calculation of the core consistency of normalized models was corrected in version 1.1.18.
