### ISSUE TITLE
Aqualog Emission Correction Range Check

### ISSUE THREAD

**Issue by jakehosen** [MatthiasPucher/staRdom#2]
Thanks for a great package! A small issue with the function "eem_spectral_cor". The function checks to see that the intervals match up for the emission and excitation correction files. For Aqualogs the emission wavelengths that are measured aren't even integers because of the array detector. This means that line 591 in "correction_functions.R" will turn up a problem even if the emission correction range is the greater than that of the sample because of this mismatch in intervals. I cloned the repo and removed this line and the problem was solved. I recommend changing line 591 to check that the correction range exceeds the sample emission range.

```
if(!all(x$ex %in% seq(xEx[1],xEx[2]))) stop("Excitation correction does not cover EEM excitation spectrum!")
if(!all(x$em %in% seq(xEm[1],xEm[2]))) stop("Emission correction does not cover EEM emission spectrum!")
```

**Comment by MatthiasPucher** [comment]
Problem with Aqualog fluorometers should be fixed in version 1.0.13.
I would appreciate, if you could test it.
And staRdom 1.0.13 requires eemR 1.0.1 (from GitHub).

**Comment by jakehosen** [comment]
It works with eem_read_csv but the eem_read function still produces that error when run with aqualog data. If you can bring back the eem_read_csv function it would be helpful!

**Comment by MatthiasPucher** [comment]
Could you please be a bit more specific so I can solve the particular problem?
Did you use the aqualog or the csv importer function when using eem_read?
What was the error?

**Comment by jakehosen** [comment]
With the eem_read_csv I was able to successfully run PARAFAC analysis without errors. With the eem_read function everything works fine until the function "eem_extend2largest". At this point the error "object ‘z’ not found" is returned.

**Comment by MatthiasPucher** [comment]
Could you maybe provide me with a file, that causes the problem? I am still not sure at what point the problem arises.
