### ISSUE TITLE
Output directory issue/ absence of results

### ISSUE THREAD

**Issue by jllavin77** [MatthiasPucher/staRdom#20]
Dear Matthias,

I've been trying to use your package to perform a PARAFAC analysis. After following the instructions given in this [vignette](https://cran.r-project.org/web//packages/staRdom/vignettes/Basic_analysis_of_DOM_samples.html) using your automated/knit script and replacing the path to the output folder in both places you state (in the vignette)  using the correct folder separator "/".
I only get a .xls table as output, which I can't use to import it via this command `eem_list <- eem_import_dir(dir)` since I only get an error related to the inability to import any data.
Should I expect a different output from the first script, apart from the excel file?
Am I missing some kind of output (a Rdata file or something like that) we should find in the working directory? 
Or can there be another issue?
Please ask for any extra info you may need to figure out what may be happening.

Thanks in advance for your kind attention.

JL

**Comment by MatthiasPucher** [comment]
@brycook
Sorry for my late answer. I could see, you managed to solve the issue with Philippe.
@jllavin77 
The scirpt returns two kinds of output. One is a list of corrected EEMs, absorbance and metadate (filename can be adjusted in line 200, default is eem_list_DATE.RData), which can be imported by the eem_import_dir() function. The other thing is the xls file you mentioned. This contains the results. If I understand your question correctly, you were looking for the results from the peak picking in another file format than xls. Is this true?
So far, no one ever asked for that and I have not thought about it myself.
If you are looking for a way to save the results from the peak picking in an RData file, you can add one line in the script to do so. Please give me some days to think about a good solution, I could add to the package.

**Comment by jllavin77** [comment]
@MatthiasPucher 
My problem is directly related with the total output expected that you described:"The scirpt returns two kinds of output. One is a list of corrected EEMs, absorbance and metadate (filename can be adjusted in line 200, default is eem_list_DATE.RData), which can be imported by the eem_import_dir() function."
I only get the xls. bot no clue about the list of corrected EEMs, absorbance and metadata. That is why I can't advence in the analysis.
Any idea of why those files are not generated? 
Thanks in advance

**Comment by MatthiasPucher** [comment]
Right now, I have no idea. Do you get any message from the knitting process, that could explain the problem?

**Comment by jllavin77** [comment]
@MatthiasPucher,
I didn't receive any special error after the knitting process...
Please find attached the output files yielded from the knitting run, in case you can use them for debugging.

Thanks in advance.
[EEM_simple_analysis.zip](https://github.com/MatthiasPucher/staRdom/files/8254031/EEM_simple_analysis.zip)

**Comment by MatthiasPucher** [comment]
I had a look at your output. You need to remove
#setwd(“C:/R_data/PARAFAC/”)
and any other R code from the markdown part of the file. R code needs to be placed in R chunks.
Also, something happened to the line
if(data_file != FALSE){
  save(list=c(eem_name,"abs_data"),file = paste0(output_dir,data_file,"_",format(Sys.time(), "%Y%m%d_%H%M%S"),".RData"))
}
This should not be where it is. I suppose, it is placed outside and R chunk.
I suppose, this solves your problems.
If you have doubts at any point in the script, you can start over with a fresh template and check the differences.
