### ISSUE TITLE
Problem using eem_import_dir

### ISSUE THREAD

**Issue by catbgun** [MatthiasPucher/staRdom#22]
Experiencing problem reading and combining eemlist files using the eem_import_dir. Capable of reading the files one by one, but not combining the files. With my limited R knowledge, I tried asking: https://stackoverflow.com/questions/71675401/what-can-be-the-problem-when-eem-import-dir-is-working-properly

**Comment by MatthiasPucher** [comment]
I could not identify your issue yet, but I uploaded a slightly changed version of eem_import_dir to GitHub. I found another issue, namely, the function reads also the exemplary eemlist provided with the package, which is fixed now. Additionally, you can use the verbose argument to get more feedback. Could you please check, if this helps you solving the problem or just tell me, if there any other or further problems.
