### ISSUE TITLE
Problems with eem_read function

### ISSUE THREAD

**Issue by RolandoSanGu** [MatthiasPucher/staRdom#23]
Dear Matthias

First I want to say thank you for the great work that you have been doing with this package. It has been helping me a lot for the last two years. Nevertheless, I recently experienced an issue with the package because I can´t run the ´eem_read´ function, even with the examples that are given on the vignettes.

I am really ashamed because probably could be a simple error, however, I am not doing this for the first time and I have already tried with several procedures but the errors are always the same:

Error in file.info(file) : invalid filename argument

Error in .eem_csv(file) : argument "file" is missing, with no default or

In advance, I would appreciate your help.

Regards

**Comment by MatthiasPucher** [comment]
This issue is addressed in another thread.
