### ISSUE TITLE
Error when calculating UV index with `abs_parms()` function

### ISSUE THREAD

**Issue by uby76** [MatthiasPucher/staRdom#24]
Hello,

I encountered an error when trying to calculate the UV index using the `abs_parms()` function in R. Below is the code I used:

[data.csv](https://github.com/user-attachments/files/18132230/data.csv)
```r
setwd("E:/data/uv") 
library(dplyr)
library(tidyr)
library("staRdom")

absorbance <- read.csv("data.csv", row.names = 1, header = T)

cores <- detectCores(logical = FALSE)
slope_parms <- abs_parms(absorbance, cuvl = 1, cores = cores)
slope_parms

write.csv(slope_parms, "slope_parms.csv")
```

**Error Message:**
```
Error in xy.coords(x, y, setLab = FALSE) : the lengths of 'x' and 'y' are not the same
```

I’ve attached my data file for reference. Could you kindly advise on how I should modify the code or what might be causing this issue? I truly appreciate the tools you have developed, they are very helpful. 

Thank you very much!

**Comment by MatthiasPucher** [comment]
Hello and thank you for the question!
The reason for this error is, that the function is using a column named "wavelength", which is not present the way you read the csv. The first column in your csv is not named at all. I made this slight correction in the attached file.
[data.csv](https://github.com/user-attachments/files/18147578/data.csv)

And you need to adapt the 6th line of your provided code as following:
absorbance <- read.csv("data.csv", header = T)

Doing this, it worked on my machine.
All the best!

**Comment by MatthiasPucher** [comment]
I will add more specific feedback in case of such an error in the next version of staRdom, so it can be traced better.
