### ISSUE TITLE
ggeem - colour palette(colpal)

### ISSUE THREAD

**Issue by liberty0117** [MatthiasPucher/staRdom#9]
Hi,
    When I use "ggeem()" to draw the final fluorescence components. Generally, we like to use the "jet" color matching in MATLAB. Does the author include jet color matching in staRdom?  Of course, this is just my personal suggestion.  Thanks for such an excellent package.

**Comment by MatthiasPucher** [comment]
Thanks for your question!
I took the opportunity to adapt the handling of colours slightly and added documentation and examples. This is available in the latest function on GitHub, CRAN will follow soon.
In your case, you can now use:
ggeem(eem, colpal = matlab::jet.colors(50))
or more generally using ggplot2 (just 1 example):
ggeem(eem)+
   scale_fill_viridis_c()+
   scale_color_viridis_c()

Fill and colour are sometimes both needed depending whether wavelength slits are equal or not!
Also the other plot functions in staRdom handle colours similarly now.

I am open to any more questions you have!

**Comment by liberty0117** [comment]
Thank you very much for your update to bring great convenience to users. This is a very good R package !


You reap what you sow.
On 4/23/2020 16:52，MatthiasPucher<notifications@github.com> wrote：

Thanks for your question!
I took the opportunity to adapt the handling of colours slightly and added documentation and examples. This is available in the latest function on GitHub, CRAN will follow soon.
In your case, you can now use:
ggeem(eem, colpal = matlab::jet.colors(50))
or more generally using ggplot2 (just 1 example):
ggeem(eem)+
scale_fill_viridis_c()+
scale_color_viridis_c()

Fill and colour are sometimes both needed depending whether wavelength slits are equal or not!
Also the other plot functions in staRdom handle colours similarly now.

I am open to any more questions you have!
